<?php

namespace Database\Seeders;

use App\Models\Ciudad;
use App\Models\Comuna;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciudad = new Ciudad;

        $nid=$ciudad->select('id')->where('nombre','=','Iquique')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Alto Hospicio';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Iquique';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Tamarugal')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Camiña';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Colchane';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Huara';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pica';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pozo Almonte';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Antofagasta')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Antofagasta';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Mejillones';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Sierra Gorda';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Taltal';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','El Loa')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Calama';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ollagüe';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Pedro de Atacama';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Tocopilla')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'María Elena';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tocopilla';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Chañaral')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chañaral';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Diego de Almagro';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Copiapó')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Caldera';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Copiapó';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tierra Amarilla';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Huasco')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Alto del Carmen';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Freirina';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Huasco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Vallenar';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Choapa')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Canela';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Illapel';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Vilos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Salamanca';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Elqui')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Andacollo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coquimbo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Higuera';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Serena';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Paihuano';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Vicuña';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Limarí')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Combarbalá';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Monte Patria';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ovalle';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Punitaqui';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Hurtado';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Cautín')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Carahue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chol Chol';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cunco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curarrehue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Freire';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Galvarino';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Gorbea';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lautaro';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Loncoche';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Melipeuco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Nueva Imperial';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Padre Las Casas';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Perquenco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pitrufquén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pucón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Saavedra';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Temuco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Teodoro Schmidt';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Toltén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Vilcún';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Villarrica';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Malleco')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Angol';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Collipulli';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curacautín';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ercilla';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lonquimay';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Sauces';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lumaco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Purén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Renaico';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Traiguén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Victoria';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Chacabuco')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Colina';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lampa';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Til Til';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Cordillera')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pirque';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puente Alto';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San José de Maipo';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Maipo')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Buin';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Calera de Tango';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Paine';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Bernardo';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Melipilla')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Alhué';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curacaví';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'María Pinto';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Melipilla';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Pedro';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Santiago')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cerrillos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cerro Navia';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Conchalí';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'El Bosque';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Estación Central';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Huechuraba';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Independencia';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Cisterna';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Florida';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Granja';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Pintana';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Reina';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Las Condes';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lo Barnechea';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lo Espejo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lo Prado';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Macul';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Maipú';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ñuñoa';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pedro Aguirre Cerda';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Peñalolén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Providencia';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pudahuel';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quilicura';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quinta Normal';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Recoleta';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Renca';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Joaquín';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Miguel';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Ramón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santiago';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Vitacura';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Talagante')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'El Monte';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Isla de Maipo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Padre Hurtado';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Peñaflor';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Talagante';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Isla de Pascua')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Rapa Nui';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Los Andes')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Calle Larga';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Andes';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Rinconada';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Esteban';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Marga Marga')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Limache';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Olmué';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quilpué';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Villa Alemana';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Petorca')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cabildo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Ligua';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Papudo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Petorca';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Zapallar';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Quillota')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Hijuelas';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Calera';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Cruz';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Nogales';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quillota';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','San Antonio')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Algarrobo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cartagena';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'El Quisco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'El Tabo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Antonio';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santo Domingo';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','San Felipe de Aconcagua')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Catemu';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Llay Llay';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Panquehue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Putaendo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Felipe';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santa María';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Valparaíso')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Casablanca';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Concón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Juan Fernández';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puchuncaví';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quintero';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Valparaíso';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Viña del Mar';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Cachapoal')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Codegua';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coinco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coltauco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Doñihue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Graneros';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Las Cabras';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Machalí';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Malloa';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Mostazal';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Olivar';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Peumo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pichidegua';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quinta de Tilcoco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Rancagua';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Rengo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Requínoa';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Vicente de Tagua Tagua';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Cardenal Caro')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Estrella';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Litueche';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Marchigüe';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Navidad';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Paredones';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pichilemu';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Colchagua')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chépica';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chimbarongo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lolol';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Nancagua';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Palmilla';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Peralillo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Placilla';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pumanque';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Fernando';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santa Cruz';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Cauquenes')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cauquenes';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chanco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pelluhue';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Curicó')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curicó';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Hualañé';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Licantén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Molina';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Rauco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Romeral';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Sagrada Familia';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Teno';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Vichuquén';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Linares')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Colbún';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Linares';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Longaví';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Parral';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Retiro';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Javier';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Villa Alegre';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Yerbas Buenas';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Talca')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Constitución';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curepto';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Empedrado';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Maule';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pelarco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pencahue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Claro';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Clemente';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Rafael';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Talca';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Arauco')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Arauco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cañete';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Contulmo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curanilahue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lebu';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Álamos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tirúa';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Bío Bío')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Alto Bío Bío';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Antuco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cabrero';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Laja';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Ángeles';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Mulchén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Nacimiento';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Negrete';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quilaco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quilleco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Rosendo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santa Bárbara';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tucapel';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Yumbel';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Concepción')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chiguayante';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Concepción';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coronel';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Florida';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Hualpén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Hualqui';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lota';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Penco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Pedro de la Paz';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Santa Juana';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Talcahuano';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tomé';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Chiloé')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ancud';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Castro';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chonchi';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Curaco de Vélez';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Dalcahue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puqueldón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Queilén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quellón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quemchi';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quinchao';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Llanquihue')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Calbuco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cochamó';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Fresia';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Frutillar';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Llanquihue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Muermos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Maullín';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puerto Montt';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puerto Varas';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Osorno')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Osorno';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puerto Octay';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Purranque';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puyehue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Negro';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Juan de la Costa';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Pablo';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Palena')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chaitén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Futaleufú';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Hualaihué';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Palena';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Aysén')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Aysén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cisnes';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Guaitecas';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Capitán Prat')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cochrane';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'O’Higgins';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Tortel';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Coyhaique')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coyhaique';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lago Verde';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','General Carrera')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chile Chico';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Ibáñez';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Antártica Chilena')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Antártica';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cabo de Hornos';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Magallanes')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Laguna Blanca';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Punta Arenas';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Verde';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Gregorio';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Tierra del Fuego')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Porvenir';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Primavera';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Timaukel';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Última Esperanza')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Puerto Natales';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Torres del Paine';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Ranco')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Futrono';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'La Unión';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lago Ranco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Río Bueno';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Valdivia')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Corral';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Lanco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Los Lagos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Máfil';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Mariquina';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Paillaco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Panguipulli';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Valdivia';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Arica')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Arica';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Camarones';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Parinacota')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'General Lagos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Putre';$comuna->save();
        
        $nid=$ciudad->select('id')->where('nombre','=','Diguillín')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Bulnes';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chillán';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Chillán Viejo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'El Carmen';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pemuco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Pinto';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quillón';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Ignacio';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Yungay';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Itata')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Cobquecura';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coelemu';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ninhue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Portezuelo';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Quirihue';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ránquil';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Trehuaco';$comuna->save();
        $nid=$ciudad->select('id')->where('nombre','=','Punilla')->get();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Coihueco';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'Ñiquén';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Carlos';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Fabián';$comuna->save();
        $comuna = new Comuna;$comuna->ciudad_id=$nid[0]->id;$comuna->nombre = 'San Nicolás';$comuna->save();
        

    }
}
